# Generated by Django 5.0 on 2023-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
