# Generated by Django 5.0 on 2024-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_test_date_alter_test_name_alter_test_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2'), ('category2', 'Category 3'), ('category2', 'Category 4')], max_length=20)),
                ('question_text', models.TextField(max_length=400)),
                ('answer1', models.TextField(max_length=200)),
                ('answer2', models.TextField(max_length=200)),
                ('answer3', models.TextField(max_length=200)),
                ('answer4', models.TextField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('answer1', 'Answer 1'), ('answer2', 'Answer 2'), ('answer3', 'Answer 3'), ('answer4', 'Answer 4')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestUserAccountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.IntegerField(default=0)),
                ('later_answers', models.BooleanField(default=False)),
                ('test_completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('result', models.FloatField(max_length=5)),
                ('time_solved', models.FloatField(max_length=5)),
                ('date_solved', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='ai_gen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='barou',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='completition_no_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='completition_time_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='newly_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='personal_gen',
            field=models.BooleanField(default=False),
        ),
    ]
