# Generated by Django 5.0 on 2024-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
