# Generated by Django 5.0 on 2024-02-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestUserAccountSession',
        ),
    ]
